config/routes.rb
Tapadeal::Application.routes.draw do
  devise_for :admins

  resources :specials

  resources :deals
  
  resources :bars

  resources :cities

  root :to => 'deals#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/bar.rb
class Bar < ActiveRecord::Base
  attr_accessible :city_id, :name
  
  belongs_to :city
  has_many :specials
  
   validates_presence_of :city_id	
end

app/models/city.rb
class City < ActiveRecord::Base
  attr_accessible :local
  
  has_many :bars
  has_many :specials
  
end

app/models/deal.rb
class Deal < ActiveRecord::Base
  
end

app/models/special.rb
class Special < ActiveRecord::Base
  attr_accessible :bar_id, :city_id, :day, :drink
  
  belongs_to :bar
  belongs_to :city
  
  validates_presence_of :bar_id	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bars_controller.rb
class BarsController < ApplicationController
  # GET /bars
  # GET /bars.json
  def index
    @bars = Bar.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bars }
    end
  end

  # GET /bars/1
  # GET /bars/1.json
  def show
    @bar = Bar.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bar }
    end
  end

  # GET /bars/new
  # GET /bars/new.json
  def new
    @bar = Bar.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bar }
    end
  end

  # GET /bars/1/edit
  def edit
    @bar = Bar.find(params[:id])
  end

  # POST /bars
  # POST /bars.json
  def create
    @bar = Bar.new(params[:bar])

    respond_to do |format|
      if @bar.save
        format.html { redirect_to @bar, notice: 'Bar was successfully created.' }
        format.json { render json: @bar, status: :created, location: @bar }
      else
        format.html { render action: "new" }
        format.json { render json: @bar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bars/1
  # PUT /bars/1.json
  def update
    @bar = Bar.find(params[:id])

    respond_to do |format|
      if @bar.update_attributes(params[:bar])
        format.html { redirect_to @bar, notice: 'Bar was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bars/1
  # DELETE /bars/1.json
  def destroy
    @bar = Bar.find(params[:id])
    @bar.destroy

    respond_to do |format|
      format.html { redirect_to bars_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  # GET /cities
  # GET /cities.json
  def index
    @cities = City.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cities }
    end
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
    @city = City.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @city }
    end
  end

  # GET /cities/new
  # GET /cities/new.json
  def new
    @city = City.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @city }
    end
  end

  # GET /cities/1/edit
  def edit
    @city = City.find(params[:id])
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(params[:city])

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'City was successfully created.' }
        format.json { render json: @city, status: :created, location: @city }
      else
        format.html { render action: "new" }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cities/1
  # PUT /cities/1.json
  def update
    @city = City.find(params[:id])

    respond_to do |format|
      if @city.update_attributes(params[:city])
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city = City.find(params[:id])
    @city.destroy

    respond_to do |format|
      format.html { redirect_to cities_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  # GET /specials
  # GET /specials.json
  helper_method :sort_column, :sort_direction
  
  
  def index
     @specials = Special.order(sort_column + ' ' + sort_direction).where("day = ?", Time.now.wday)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @specials }
	end
  end
  
  def show
    @upcoming = Special.order(sort_column + ' ' + sort_direction).where("day >= ?", Time.now.wday)
  end 
  private
  def sort_column
    Special.column_names.include?(params[:sort]) ? params[:sort] : "bar_id"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"  
  end
end

app/controllers/specials_controller.rb
class SpecialsController < ApplicationController
  # GET /specials
  # GET /specials.json
  def index
    @specials = Special.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @specials }
    end
  end

  # GET /specials/1
  # GET /specials/1.json
  def show
    @special = Special.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @special }
    end
  end

  # GET /specials/new
  # GET /specials/new.json
  def new
    @special = Special.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @special }
    end
  end

  # GET /specials/1/edit
  def edit
    @special = Special.find(params[:id])
  end

  # POST /specials
  # POST /specials.json
  def create
    @special = Special.new(params[:special])

    respond_to do |format|
      if @special.save
        format.html { redirect_to @special, notice: 'Special was successfully created.' }
        format.json { render json: @special, status: :created, location: @special }
      else
        format.html { render action: "new" }
        format.json { render json: @special.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /specials/1
  # PUT /specials/1.json
  def update
    @special = Special.find(params[:id])

    respond_to do |format|
      if @special.update_attributes(params[:special])
        format.html { redirect_to @special, notice: 'Special was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @special.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /specials/1
  # DELETE /specials/1.json
  def destroy
    @special = Special.find(params[:id])
    @special.destroy

    respond_to do |format|
      format.html { redirect_to specials_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
	module ApplicationHelper
	  def sortable(column, title = nil)
		title ||= column.titleize
		direction = (column == sort_column && sort_direction == "asc") ? "desc" : "asc"
		link_to title, :sort => column, :direction =>direction
	  end
	  def full_title(page_title)
		base_title = "Tap A Deal"
		if page_title.empty?
		  base_title
		else
		  "#{base_title} | #{page_title}"
		end
	  end
	end

app/helpers/bars_helper.rb
module BarsHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/specials_helper.rb
module SpecialsHelper
end

app/views/bars/_form.html.erb
<%= form_for(@bar) do |f| %>
  <% if @bar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bar.errors.count, "error") %> prohibited this bar from being saved:</h2>

      <ul>
      <% @bar.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= collection_select(:bar, :city_id, City.all, :id, :local, :prompt => 'Select City') %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bars/edit.html.erb
<h1>Editing bar</h1>

<%= render 'form' %>

<%= link_to 'Show', @bar, :class => 'btn' %> |
<%= link_to 'Back', bars_path, :class => 'btn' %>

app/views/bars/index.html.erb
<h1>Listing bars</h1>

<table class="table">
  <tr>
    <th>Name</th>
    <th>City</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bars.each do |bar| %>
  <tr>
    <td><%= bar.name %></td>
    <td><%= bar.city.local %></td>
    <td><%= link_to 'Show', bar, :class => 'btn' %></td>
    <td><%= link_to 'Edit', edit_bar_path(bar), :class => 'btn' %></td>
    <td><%= link_to 'Destroy', bar, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-destroy' %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bar', new_bar_path, :class => 'btn' %>

app/views/bars/new.html.erb
<h1>New bar</h1>

<%= render 'form' %>

<%= link_to 'Back', bars_path, :class => 'btn' %>

app/views/bars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @bar.name %>
</p>

<p>
  <b>City:</b>
  <%= @bar.city_id %>
</p>


<%= link_to 'Edit', edit_bar_path(@bar), :class => 'btn' %>
<%= link_to 'Back', bars_path, :class => 'btn' %>

app/views/cities/_form.html.erb
<%= form_for(@city) do |f| %>
  <% if @city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
      <% @city.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :local %><br />
    <%= f.text_field :local %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cities/edit.html.erb
<h1>Editing city</h1>

<%= render 'form' %>

<%= link_to 'Show', @city, :class => 'btn' %> |
<%= link_to 'Back', cities_path, :class => 'btn' %>

app/views/cities/index.html.erb
<h1>Listing cities</h1>

<table class="table">
  <tr>
    <th>Local</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cities.each do |city| %>
  <tr>
    <td><%= city.local %></td>
    <td><%= link_to 'Show', city, :class => 'btn' %></td>
    <td><%= link_to 'Edit', edit_city_path(city), :class => 'btn' %></td>
    <td><%= link_to 'Destroy', city, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New City', new_city_path, :class => 'btn' %>

app/views/cities/new.html.erb
<h1>New city</h1>

<%= render 'form' %>

<%= link_to 'Back', cities_path, :class => 'btn' %>

app/views/cities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Local:</b>
  <%= @city.local %>
</p>


<%= link_to 'Edit', edit_city_path(@city) %> |
<%= link_to 'Back', cities_path %>

app/views/deals/index.html.erb
<style>
	.box { background: #3299CC}
    body { color:  #FFFFFF;
		 background: #236B8E;}
	p { font-size: 15px;
    	  color: #FFFFFF}
</style>

<div class="container-fluid">
    <h1>What's on Tap Today</h1>
    <br>
    </br>
	  <div class="row-fluid">
       <div class="span12 well well-large img-polaroid box">
        <% for s in @specials %>
		</br>
        <p>
        <%= s.drink %> at <%= link_to s.bar.name %>
        </p>
	    <%end%>
        </div>
    </div>  
    <h4>Sort by <%= sortable "bar_id"%></h4>
</div>

app/views/deals/show.html.erb
<h1>What's Coming Up</h1>
<br>
</br>
<h4>Sort by <%= sortable "bar_id" %> or <%= sortable "day" %>
</h4>
<% for s in @upcoming %>
<p>
<%= s.drink %> at <%= link_to s.bar.name %> on <%= Date::DAYNAMES[s.day.to_i] %>
</p>

<% end %>

app/views/deals/upcoming.html.erb
<h1>What's Coming Up</h1>
<br>
</br>
<% for s in @specials %>
<p>
<%= s.drink %> at <%= link_to s.bar.name %>
</p>
<h4>Sort by <%= sortable "bar_id" %>
</h4>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tap A Deal</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>
<div class="navbar">
  <div class="navbar-inner well">
    <ul class="nav nav-pills">
		<li class="active">
			<a href="#"><strong>Tap A Deal</strong></a>
			</li>
		<li><a href="#">Deals by Bar</a></li>
		<li><a href="#">Deals by Day</a></li>
	</ul>
 </div>
 
<div id="landing" class="row-fluid center">
  <div class="span5 offset2">
    <%= yield %>
	</div>
  <div id="sidebar" class="span3">
	<div id="map" class="span12">
		<iframe width='300' height='300' frameBorder='1' src='http://a.tiles.mapbox.com/v3/drewablo.springfield_il_bars.html#12/39.7988/-89.6515'></iframe>
	</div>
	

</body>
</html>

app/views/specials/_form.html.erb
<%= form_for(@special) do |f| %>
  <% if @special.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@special.errors.count, "error") %> prohibited this special from being saved:</h2>

      <ul>
      <% @special.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :drink %><br />
    <%= f.text_field :drink %>
  </div>
  <div class="field">
    <%= f.select :day, Date::DAYNAMES.zip((0..6).to_a), :prompt => 'Select Day' %>
  </div>
  <div class="field">
    <%= collection_select(:special, :bar_id, Bar.all, :id, :name, :prompt => 'Select Bar') %>
  </div>
  <div class="field">
     <%= collection_select(:special, :city_id, City.all, :id, :local, :prompt => 'Select City') %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/specials/edit.html.erb
<h1>Editing special</h1>

<%= render 'form' %>

<%= link_to 'Show', @special %> |
<%= link_to 'Back', specials_path %>

app/views/specials/index.html.erb
<h1>Listing specials</h1>

<table class ="table">
  <tr>
    <th>Drink</th>
    <th>Day</th>
    <th>Bar</th>
    <th>City</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @specials.each do |special| %>
  <tr>
    <td><%= special.drink %></td>
    <td><%= special.day %></td>
    <td><%= special.bar.name %></td>
    <td><%= special.city.local %></td>
    <td><%= link_to 'Show', special, :class => 'btn' %></td>
    <td><%= link_to 'Edit', edit_special_path(special), :class => 'btn' %></td>
    <td><%= link_to 'Destroy', special, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-danger' %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Special', new_special_path, :class => 'btn' %>

app/views/specials/new.html.erb
<h1>New special</h1>

<%= render 'form' %>

<%= link_to 'Back', specials_path %>

app/views/specials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Drink:</b>
  <%= @special.drink %>
</p>

<p>
  <b>Day:</b>
  <%= @special.day %>
</p>

<p>
  <b>Bar:</b>
  <%= @special.bar_id %>
</p>

<p>
  <b>City:</b>
  <%= @special.city_id %>
</p>


<%= link_to 'Edit', edit_special_path(@special), :class => 'btn' %> |
<%= link_to 'Back', specials_path, :class => 'btn' %>